//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectionPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terror
    {
        public int Id { get; set; }
        public string Personals { get; set; }
        public string IP_Addresses { get; set; }
    }
}
